### ISSUE TITLE
Calendar timezone dropdown

### ISSUE THREAD

**Issue by cornae** [syslabcom/DevDes#4]
The calendar timezone dropdown is broken. I discovered this while creating the storyboard for event sharing.

**Comment by cornae** [comment]
I took the liberty to repair it.

**Comment by pilz** [comment]
@cornae something we have to do or was that css only?

**Comment by cornae** [comment]
That was CSS only. Worth checking though if it looks and functions fine on both Proto and DEV still.

**Comment by pilz** [comment]
Ok, thank you, will check!
